### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by cschiri** [NDelventhal/cot_reports#2]
Regards

I downloaded the zip file with the setup.py file. I ran into issues when I tried to install the package as follows:

```
(base) C:\Users\ixe\Downloads\cot-reports-main>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    long_description=open('README.md').read(),
  File "C:\Users\ixe\Anaconda3\lib\encodings\cp1252.py", line 23, in decode

    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 16660: ch
aracter maps to <undefined>

(base) C:\Users\ixe\Downloads\cot-reports-main>`
```

This is the first time I have ever encountered the error. Can you help?

**Comment by cschiri** [comment]
Resolved by:

1.  Opening the README.txt file.
2.  Clicking "Save As"
3.  Under the "Encoding" option, select "Unicode".

The problem stemmed from the encoder failing to read in a table.
