### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ValueRaider** [NDelventhal/cot_reports#8]
First-time user, tried running the first example and immediately blows up:

``` Python
import cot_reports as cot
df = cot.cot_hist(cot_report_type= 'traders_in_financial_futures_futopt')
```

> Selected: COT Traders in Financial Futures report. Futures and Options.
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
>     httplib_response = self._make_request(
>                        ^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
>     self._validate_conn(conn)
>   File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
>     conn.connect()
>   File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 358, in connect
>     self.sock = conn = self._new_conn()
>                        ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff294dd3910>: Failed to establish a new connection: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
>     resp = conn.urlopen(
>            ^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
>     retries = retries.increment(
>               ^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cftc.gov', port=443): Max retries exceeded with url: /files/dea/history/fin_com_txt_2006_2016.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff294dd3910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/user1/.local/lib/python3.11/site-packages/cot_reports/cot_reports.py", line 74, in cot_hist
>     req = requests.get(cot_url) 
>           ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
>     return request("get", url, params=params, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 565, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cftc.gov', port=443): Max retries exceeded with url: /files/dea/history/fin_com_txt_2006_2016.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff294dd3910>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by ValueRaider** [comment]
False alarm, something was blocking access.
